config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :users, only: %i[show edit update index]
  resources :microposts, only: %i[create destroy index]

  resources :users do
    member do
      get :following, :followers, :likes
    end
  end

  resources :microposts do
    member do
      get :liked
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :notifications, only: :index

  root 'static_pages#home' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :profile_picture, ProfilePictureUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  has_many :microposts, dependent: :destroy

  has_many :comments, dependent: :destroy
  # has_many :relationships, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: :follower_id,
                                  dependent: :destroy
  # 僕のフォローしている人たち(さらなる簡略化)
  # @user.active_relationships.map {|r| r.followed }
  # @user.following
  has_many :following,
           through: :active_relationships,
           source: :followed

  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: :followed_id,
                                   dependent: :destroy

  # 僕のフォロワーいちらん
  has_many :followers,
           through: :passive_relationships,
           source: :follower

  has_many :likes_relationships, class_name: 'Like',
                                 foreign_key: :user_id,
                                 dependent: :destroy

  # ユーザーがいいねしている投稿一覧
  has_many :likes,
           through: :likes_relationships,
           source: :micropost

  # 通知
  # 自分(=give_id)が（誰かに）与えた通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'give_id', dependent: :destroy
  # 自分宛(=given_id)の通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'given_id', dependent: :destroy

  # 新規作成・更新時
  # コールバック=>
  before_save { self.email = email.downcase }

  # 新規作成時のみ（更新時は反応しない）
  # before_create :create_activation_digest

  # Validation
  validates :full_name, presence: true, length: { maximum: 50 }

  INVALID_NAME_REGEX = /( |　)+/.freeze
  validates :user_name, presence: true, length: { maximum: 30 },
                        uniqueness: true,
                        format: { without: INVALID_NAME_REGEX }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # フォロー関連
  def follow(user)
    # self.active_relationships.create(followed_id: user.id)
    # self.following << user
    following << user
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # お気に入り関連
  def add_like(post)
    likes << post
  end

  def remove_like(post)
    likes_relationships.find_by(micropost_id: post.id).destroy
  end

  def likes?(post)
    likes.including?(post)
  end

  # コメント関連
  def add_comment(comment, post); end

  def remove_comment(comment, post); end

  # 通知関連 current_userがuserをフォローした時userに通知する
  def create_notification_follow!(current_user)
    temp = Notification.where(['give_id = ? and given_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        given_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /users/sign_up
  # def new
  #  super
  # end

  # POST /users
  # def create
  #   super
  # end

  # GET /users/edit
  # def edit
  #  super
  # end

  # PUT /resource
  # def update
  #  super
  # end

  # DELETE /resource
  # def destroy
  #  super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #  devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_action :require_no_authentication

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # ログインしているか
  before_action :authenticate_user!, only: %i[update edit show index following followers likes]
  # 自分自身かどうか
  before_action :correct_user, only: %i[update edit destroy]

  # GET /users/:id
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    # 一覧画面からもコメントを送る
    @comment = current_user.comments.build
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PATCH /users/:id
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params_update)
      redirect_to @user
    else
      # Failure
      # => @user.errors.full_messages()
      render 'edit'
    end
  end

  # DELETE /users/:id
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end

  # GET /users
  def index
    @users = User.all.paginate(page: params[:page])
  end

  # フォローしている人一覧
  # GET /users/:id/following
  def following
    @title = 'フォロー'
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  # フォロワー一覧
  # GET /users/:id/follower
  def followers
    @title = 'フォロワー'
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  # いいね一覧
  # GET /users/:id/likes
  def likes
    @title = 'お気に入り'
    @user = User.find(params[:id])
    @posts = @user.likes.paginate(page: params[:page])
    @comment = current_user.comments.build
    render 'show_like'
  end

  private

  def user_params_update
    params.require(:user).permit(:full_name, :user_name, :email, :gender,
                                 :website, :introduction, :profile_picture)
  end

  # 他人の編集ページに直接アクセスした場合
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user == @user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary follow-btn btn-lg" %>
<% end %>

app/views/users/_like.html.erb
<%= form_for(current_user.likes_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
  <%= button_tag(class: "like-btn" ) do %>
    <div class = "glyphicon glyphicon-heart-empty"></div>
  <% end %>
<% end %>

app/views/users/_like_form.html.erb
<span class="like" id="like_form">
  <% if micropost.liked_by.include?(current_user) %>
    <%= render 'users/unlike', micropost: micropost %>
  <% else %>
    <%= render 'users/like', micropost: micropost %>
  <% end %>
</span>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn unfollow-btn btn-lg" %>
<% end %>

app/views/users/_unlike.html.erb
<%= form_for(current_user.likes_relationships.find_by(micropost_id: micropost.id), 
                  html: { method: :delete }, remote: true) do |f| %>
  <%= button_tag(class: "like-btn") do %>
  <div class = "glyphicon glyphicon-heart"></div>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.full_name, user %>
  <% #if current_user.admin? && !current_user?(user) %>
    <% #link_to "delete", user_path(user), method: :delete,
                                  #data: { #confirm: "You sure?" } %>
  <% #end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'ユーザ情報編集') %>

<div class="row">
<div class="col-md-6 col-md-offset-3">
<h2>ユーザ情報編集</h2>
<ul class="nav nav-tabs m-2">
    <li class="nav-item"><a class="nav-link text-success font-weight-light" href="<%= edit_user_url(current_user) %>">プロフィール編集</a></li>
    <li class="nav-item"><a class="nav-link active font-weight-bold text-success" href="<%= edit_user_registration_url %>">パスワード変更</a></li>
</ul> 

<%= form_for(@user) do |f| %>

<h3>公開情報</h3>
  <div class="field">
    <%= f.label "プロフィール画像" %><br />
    <span class="picture">
      <%= f.file_field :profile_picture %>
    </span>
  </div>
  
  <div class="field">
    <%= f.label "フルネーム" %><br />
    <%= f.text_field :full_name, autofocus: true, autocomplete: "Full Name" %>
  </div>
  
  <div class="field">
    <%= f.label "ユーザネーム" %><br />
    <%= f.text_field :user_name, autofocus: true, autocomplete: "User Name" %>
  </div>

  <div class="field">
    <%= f.label "ウェブサイト" %><br />
    <%= f.text_field :website, autofocus: true, autocomplete: "Website" %>
  </div>
  
  <div class="field">
    <%= f.label "自己紹介" %><br />
    <%= f.text_field :introduction, autofocus: true, autocomplete: "Introduction" %>
  </div>
  
<h3>非公開情報</h3> 
    
  <div class="field">
    <%= f.label "メールアドレス" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>
  
   <div class="field">
    <%= f.label "性別" %><br />
    <label><%= f.radio_button :gender, 0 %> 回答しない </label>
    <label><%= f.radio_button :gender, 1 %> 男性 </label>
    <label><%= f.radio_button :gender, 2 %> 女性 </label>
  </div>
  
  <div class="btn">
    <div class="actions">
      <%= f.submit "プロフィールを変更",class: "btn-lg" %>
    </div>
  </div>
<% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'おすすめユーザ') %>
<h1>おすすめユーザ</h1>
 
<div class="user-index">     
<%= will_paginate @users %>

<ul class="users">
  <% @users.each do |user| %>
    <div>
      <% unless current_user == user %>
       <%= link_to user.user_name, user_path(user) %>
      <% end %>
    </div>
  <% end %>
</ul>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<div class = "show">

<!--ユーザ情報表示 -->

<div class= "show-user-info">
  <div class="show-user-info__pic">
    <% @user.profile_picture.blank? ? profile_picture = 'default.png' :  profile_picture = @user.profile_picture %>
    <%= image_tag profile_picture %>
  </div>
  <div class="show-user-info__txt">
    <div class="username">
      <%= @user.user_name %>
    </div>
    <div class="show-follow"><%= render 'shared/follow_form' if user_signed_in? %></div>
    <div><%= render 'shared/stats', class: "stats" %></div>
    <div class="fullname"><%= @user.full_name %></div>
    
    <div class="introduction">
      <%= @user.introduction unless @user.introduction.nil? %>
  　</div>
  </div>

</div>

<div class="show-user-edit">
<% if user_signed_in? && current_user.id == @user.id%>
<%= link_to "編集", edit_user_path(@user) %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<%= link_to "アカウント削除", user_path(@user), method: :delete %>
<% end %>
</div>

<!--投稿表示 -->
  <div class = "show-post">
  <% if @user.microposts.any? %>
    <h3>投稿一覧 (<%= @user.microposts.count %>)</h3>
      <ol class="wrapper">
      <% @microposts.each do |micropost| %>
        <a href = "#" data-toggle="modal" data-target = "#micropostModal">
          <div class = "micropost">
            <%= image_tag micropost.picture, class: "image" %>
          </div>
        </a>
      
     <!-- Modal -->
      <div class="modal fade" id="micropostModal" tabindex="-1" role="dialog" aria-labelledby="exampleMdalLabel" aria-hidden="true">
        <div class="modal-dialog modal-width" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <%= render 'microposts/micropost', micropost: micropost %>
            </div>
          </div>
        </div>
      </div>
      
  
    

      <% end %>
      </ol>
    <%= will_paginate @microposts %>
  <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.full_name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/show_like.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.full_name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @posts.any? %>
      <ul class="users follow">
        <%= render @posts %>
      </ul>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>