config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :users, only: %i[show edit update index]
  resources :microposts, only: %i[create destroy index]

  resources :users do
    member do
      get :following, :followers, :likes
    end
  end

  resources :microposts do
    member do
      get :liked
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :notifications, only: :index

  root 'static_pages#home' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
end

app/views/shared/_comment_form.html.erb
<div class="comment_form">
<%= form_for(@comment) do |f| %>
  <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "コメントを投稿しましょう" %>
  </div>
  <div class="btn">
    <div class="actions">
      <%= f.submit "投稿", class:"btn-sm text-center" %>
    </div>
  </div>
<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<div>
<% if @feed_items.any? %>
    <% @feed_items.each do |micropost|%>
        <div>
          <%= render micropost %>
        </div>
        <!-- Modal -->
      <div class="modal fade" id="feedModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <%= render 'microposts/micropost', micropost: micropost %>
            </div>
          </div>
        </div>
      </div>
      
      
    <% end %>
  <%= will_paginate @feed_items %>
<% end %>
</div>

app/views/shared/_follow_form.html.erb
<% unless current_user.id == @user.id %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "文章を追加..." %>
  </div>
  
  <div class = "btn">
    <%= f.submit "Post", class: "btn-lg" %>
  </div>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a href="<%= likes_user_path(@user) %>">
    <strong id="likes" class="stat">
      <%= @user.likes.count %>
    </strong>
    Likes
  </a>
</div>


<!-- non dry Modal -->


      

app/views/shared/_user_info.html.erb
  <% current_user.profile_picture ? profile_picture = 'default.png' :  profile_picture = @user.profile_picture %>
  <%= image_tag profile_picture, class: "user_info__pic" %>

    <div class="user-info__name">
      <h1><%= link_to current_user.user_name, current_user %></h1>
      <h3><%= current_user.full_name %></h3>
    </div>
  <span><%= pluralize(current_user.microposts.count, "micropost") %></span>