config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :users, only: %i[show edit update index]
  resources :microposts, only: %i[create destroy index]

  resources :users do
    member do
      get :following, :followers, :likes
    end
  end

  resources :microposts do
    member do
      get :liked
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :notifications, only: :index

  root 'static_pages#home' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
 <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
   <nav class="navbar-fixed-bottom"> 
      <% if user_signed_in? %>
            <%= link_to "投稿", new_micropost_path %>
        
        <% else %>
          投稿するには<%= link_to "ログイン", new_user_session_path %>してください
      <% end %>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "Fake Instagram", root_path, id: "logo" %>
   
    <nav>
      <ul class="navbar-right flex-container">
        <% if user_signed_in? %>
          <li>
            <div class="search-form mx-auto">
                <%= form_with url: microposts_path, html: {method: 'get'}, local: true do |form| %>
                 <%= form.text_field :search, placeholder: "ユーザ・投稿を検索", class: "serch-field" %>
                 <% form.submit "検索", class: "search-btn"%>
                <% end %>
            </div>
          </li>
          <li class="nav-link"><%= link_to "おすすめユーザ", users_path %></li>
          <li class="nav-link"><%= link_to "通知", notifications_path %></li>
          <li class="nav-link"><%= link_to "マイページ", user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('favicon.ico') %>
    <title><%= full_title(yield(:title)) %></title>    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>